Add MS SQL Server
ThinkR-open/bank pull request #8
Opened 2021-12-14 09:06 UTC by ggpinto

Hi,

I have implemented MS SQL Server as a backend (probably there was a better way, but I am not that good with R6 yet). What I did:

- Created `cache_ms_sql` based on `cache_ms_postgres`
- Created tests for `cache_ms_sql` based on `cache_ms_postgres`
- Updated the documentation

2021-12-17 15:33 UTC, ColinFay commented
Planning on reviewing this PR next week, will try on monday.

2021-12-17 21:47 UTC, ggpinto commented
Next week I’ll have more time and can redo it inheriting a class instead of rewriting it, if it can wait a bit I might come back with a better solution 😊

2021-12-21 13:24 UTC, ggpinto commented
Hi Colin, I don’t think I can use inheritance without having to change the code for PostgreSQL too, it would be a more elegant solution (mainly to detect if the needed packages are installed and to deal with different SQL data types). Just tell me what you prefer.

2021-12-24 09:58 UTC, ColinFay commented on DESCRIPTION
>      mongolite (>= 2.2.0),
These packages were put inside `Suggests` instead of `Imports` on purpose, can you put them back there? Thanks :)

2021-12-24 10:09 UTC, ColinFay reviewed
Thank you very much @ggpinto, that's awesome ! 

I feel like most methods can be inherited from `postgres` so as far as possible I'd love them to be passed from `postgres` to `ms-sql`.

Given that there might be other SQL backend at some point I'll probably write a real parent class for the two, but for now you can make ms-sql inherit from `postgres` :) 

Thanks again, awesome work.

2021-12-24 10:09 UTC, ColinFay commented on R/ms-sql.R
> +  "cache_ms_sql",
Add here `inherit = "cache_postgres"`

2021-12-24 10:09 UTC, ColinFay commented on R/ms-sql.R
> +    has_key = function(key) {
`ms-sql$has_key` is the same as `postgres$has_key` so there is no need to redefine here (will be passed through inheritance).

2021-12-24 10:09 UTC, ColinFay commented on R/ms-sql.R
> +    get = function(key) {
`ms-sql$get` is the same as `postgres$get` so there is no need to redefine here (will be passed through inheritance).

2021-12-24 10:09 UTC, ColinFay commented on R/ms-sql.R
> +    set = function(key, value) {
`ms-sql$set` is the same as `postgres$set` so there is no need to redefine here (will be passed through inheritance).

2021-12-24 10:09 UTC, ColinFay commented on R/ms-sql.R
> +    remove = function(key) {
`ms-sql$remove` is the same as `postgres$remove` so there is no need to redefine here (will be passed through inheritance).

2021-12-24 10:09 UTC, ColinFay commented on R/ms-sql.R
> +    keys = function() {
`ms-sql$keys` is the same as `postgres$keys` so there is no need to redefine here (will be passed through inheritance).

2021-12-24 10:09 UTC, ColinFay requested changes
Thank you very much @ggpinto, that's awesome ! 

I feel like most methods can be inherited from `postgres` so as far as possible I'd love them to be passed from `postgres` to `ms-sql`.

Given that there might be other SQL backend at some point I'll probably write a real parent class for the two, but for now you can make ms-sql inherit from `postgres` :) 

Thanks again, awesome work.

2021-12-27 13:45 UTC, ggpinto commented
With free time I have tried a new approach (that can maybe used as parent for all SQL classes in the future), I am sending a new PR

2021-12-27 13:45 UTC, closed without merging